### ISSUE TITLE
Increase size limits for Vaadin Upload

### ISSUE THREAD

**Issue by sgroh** [sdhealthconnect/leap-consent-ui#97]
Set the maximum file size that spring boot can handle in a MultipartFile to 5MB as per @ddecouteau request

**Comment by mojitoj** [comment]
@sgroh has this been addressed in the deployed version?

**Comment by sgroh** [comment]
yes, It' s on the application.properties file that is being used by the application
These are the properties needed that are used locally and in the deployed version : 
```
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
```
